// MBTI 궁합
Map<String, List<String>> mbtiCompatibility = {
  "goodESTJ": ["INTP","ISFP","ISTP","ISFJ"],
  "badESTJ": ["INFP","ENFP","INFJ","ENFJ"],
  "goodESTP": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "badESTP": ["INFP","ENFP","INFJ","ENFJ"],
  "goodESFJ": ["ISFP","ESFP","ISTP","ESTP"],
  "badESFJ": ["INFP","ENFP","INFJ","ENFJ"],
  "goodESFP": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "badESFP": ["INFP","ENFP","INFJ","ENFJ"],
  "goodENTJ": ["INTJ","ENTJ","INTP","ENTP"],
  "badENTJ": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "goodENTP": ["INFJ","ENTJ","INTJ","ENTP"],
  "badENTP": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "goodENFJ": ["INFP","ENTJ","INTP","ENTP"],
  "badENFJ": ["ESTJ","ESFP","ISTP","ESTP"],
  "goodENFP": ["INFJ","INTJ","INFP","INTJ"],
  "badENFP": ["ESTJ","ESFP","ISTP","ESTP"],
  "goodISTJ": ["ISFP","ESFP","ISTP","ESTP"],
  "badISTJ": ["INFP","ENFP","INFJ","ENFJ"],
  "goodISTP": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "badISTP": ["INFP","ENFP","INFJ","ENFJ"],
  "goodISFJ": ["ISFP","ESFP","ISTP","ESTP"],
  "badISFJ": ["INFP","ENFP","INFJ","ISFP"],
  "goodISFP": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "badISFP": ["INFP","ENFP","INFJ","ENFJ"],
  "goodINTJ": ["ENFP","INFJ","ENFJ","INTP"],
  "badINTJ": ["ISFJ","ESFJ","ISTJ","ESTJ"],
  "goodINTP": ["INTJ","ENTJ","INTP","ENTP"],
  "badINTP": ["ISFJ","ESFJ","ISTJ"],
  "goodINFJ": ["INFP","ENTJ","INTP","ENTP"],
  "badINFJ": ["ESTJ","ESFP","ISTP","ESTP"],
  "goodINFP": ["INTJ","ENTJ","INTP","ENTJ"],
  "badINFP": ["ESTJ","ESFP","ISTP","ESTP"],
};